"""Q42 -- 42 over C.  Values, unitary primitives, and the evaluator.

42 is interpreted in Rel: matrices over the Boolean semiring.  Q42 is
interpreted in Unitary: finite-dimensional Hilbert spaces and unitary maps,
matrices over C.  See Q42.md for the design and its provenance; the short
version is that 42's primitive set is a presentation of a *rig groupoid*, and
Carette, Heunen, Kaarsgaard & Sabry (POPL 2024) showed that a rig groupoid plus
two maps and three equations is computationally universal for quantum computing.
Those two maps are `omega` and `v` below.

What is reused from rel42, unchanged:

    core.Value      the universe generated by 0, 1, +, x
    core.Term       the abstract syntax
    core.dagger     inversion -- the *same function*, not a reimplementation
    syntax          the lexer and parser, given Q42's primitive names
    types           unification and inference, given Q42's primitive schemes

What is new here: the primitive table (adjoints rather than converses) and an
evaluator whose columns are amplitudes rather than sets.

Two constructors of the shared term language are rejected rather than
interpreted.  `Union` (`|`) and `Star` (`^`) are exactly the two whose meaning
depends on addition in the semiring being *idempotent* -- `f | f` would denote
`2f`, and `Star`'s saturation is a least fixed point needing `1 + 1 = 1`.  C's
addition is not idempotent, so neither survives, and no design judgement is
involved.  Note that dropping `|` costs nothing in expressiveness: superposition
comes from applying `v` to a basis state, not from a choice construct.
"""

from __future__ import annotations

import cmath
from typing import Callable, Dict, Tuple

from rel42.core import (
    App,
    Fun,
    Inl,
    Inr,
    Pair,
    Prim,
    Prod,
    Ref,
    Rel42Error,
    Seq,
    Star,
    Sum,
    Term,
    UNIT,
    Union,
    Unit,
    Value,
    dagger,
)

__all__ = [
    "PRIMS",
    "Q42Error",
    "Vec",
    "ZERO",
    "ONE",
    "OMEGA",
    "V_MATRIX",
    "apply_vec",
    "column",
    "dagger",
    "matrix",
    "marginal",
    "normalise",
    "probabilities",
    "sample",
    "validate",
]


class Q42Error(Rel42Error):
    pass


# A vector: basis value -> amplitude.  Absent keys are zero.
Vec = Dict[Value, complex]

TOL = 1e-12

ZERO: Value = Inl(UNIT)  # |0>
ONE: Value = Inr(UNIT)  # |1>
BIT = [ZERO, ONE]


def normalise(v: Vec) -> Vec:
    """Drop amplitudes that are zero to within tolerance."""
    return {k: z for k, z in v.items() if abs(z) > TOL}


# ---------------------------------------------------------------------------
# Primitives.  Each is a pair (forward, backward) from a basis value to a
# *column*.  The backward leg is the adjoint, where 42's was the converse --
# that substitution is the whole of the semiring change at this level.
# ---------------------------------------------------------------------------

PRIMS: Dict[str, Tuple[Callable[[Value], Vec], Callable[[Value], Vec]]] = {}


def _prim(name: str, fwd, bwd) -> None:
    PRIMS[name] = (fwd, bwd)


def _one(v: Value) -> Vec:
    return {v: 1 + 0j}


_prim("id", _one, _one)


# additive structure --------------------------------------------------------
def _swapsum(v: Value) -> Vec:
    match v:
        case Inl(x):
            return {Inr(x): 1 + 0j}
        case Inr(x):
            return {Inl(x): 1 + 0j}
    return {}


_prim("swapsum", _swapsum, _swapsum)  # self-inverse; this is Pauli X


def _assocsum(v: Value) -> Vec:  # a + (b + c)  ->  (a + b) + c
    match v:
        case Inl(x):
            return {Inl(Inl(x)): 1 + 0j}
        case Inr(Inl(x)):
            return {Inl(Inr(x)): 1 + 0j}
        case Inr(Inr(x)):
            return {Inr(x): 1 + 0j}
    return {}


def _assocsum_b(v: Value) -> Vec:
    match v:
        case Inl(Inl(x)):
            return {Inl(x): 1 + 0j}
        case Inl(Inr(x)):
            return {Inr(Inl(x)): 1 + 0j}
        case Inr(x):
            return {Inr(Inr(x)): 1 + 0j}
    return {}


_prim("assocsum", _assocsum, _assocsum_b)

_prim(
    "unitsum",  # 0 + a  <->  a;  the 0 side is uninhabited
    lambda v: {v.v: 1 + 0j} if isinstance(v, Inr) else {},
    lambda v: {Inr(v): 1 + 0j},
)


# multiplicative structure --------------------------------------------------
def _swapprod(v: Value) -> Vec:
    return {Pair(v.b, v.a): 1 + 0j} if isinstance(v, Pair) else {}


_prim("swapprod", _swapprod, _swapprod)  # self-inverse; this is SWAP


def _assocprod(v: Value) -> Vec:  # (a, (b, c))  ->  ((a, b), c)
    match v:
        case Pair(a, Pair(b, c)):
            return {Pair(Pair(a, b), c): 1 + 0j}
    return {}


def _assocprod_b(v: Value) -> Vec:
    match v:
        case Pair(Pair(a, b), c):
            return {Pair(a, Pair(b, c)): 1 + 0j}
    return {}


_prim("assocprod", _assocprod, _assocprod_b)

_prim(
    "unitprod",  # 1 x a  <->  a
    lambda v: {v.b: 1 + 0j} if isinstance(v, Pair) and v.a == UNIT else {},
    lambda v: {Pair(UNIT, v): 1 + 0j},
)


# distributivity -- and, via `mat` in gates.42, every controlled gate ---------
def _dist(v: Value) -> Vec:  # (a + b) x c  ->  (a x c) + (b x c)
    match v:
        case Pair(Inl(a), c):
            return {Inl(Pair(a, c)): 1 + 0j}
        case Pair(Inr(b), c):
            return {Inr(Pair(b, c)): 1 + 0j}
    return {}


def _dist_b(v: Value) -> Vec:
    match v:
        case Inl(Pair(a, c)):
            return {Pair(Inl(a), c): 1 + 0j}
        case Inr(Pair(b, c)):
            return {Pair(Inr(b), c): 1 + 0j}
    return {}


_prim("dist", _dist, _dist_b)


# ---------------------------------------------------------------------------
# The two generators.  Everything above is a permutation matrix and would mean
# the same thing over any semiring; these two are what C buys.
#
#   (E1)  omega^8 = id
#   (E2)  v ; v = swapsum
#   (E3)  v ; S ; v = omega^2 . (S ; v ; S)      where  S = id + omega^2
#
# (E1) and (E2) only assert that the square roots exist.  (E3) is the one that
# does work: without it `omega = id` is consistent and the model is not
# universal.  It says the pi/2 rotations decompose alike along ZXZ and XZX,
# which is the Euler decomposition of the Hadamard gate.
# ---------------------------------------------------------------------------

OMEGA = cmath.exp(1j * cmath.pi / 4)  # a primitive 8th root of unity

_prim(
    "omega",
    lambda v: {UNIT: OMEGA} if isinstance(v, Unit) else {},
    lambda v: {UNIT: OMEGA.conjugate()} if isinstance(v, Unit) else {},
)

# V = H . diag(-1, i) . H, in the basis |0> = Inl (), |1> = Inr ().  Any square
# root of X satisfies (E2); this is the one that also satisfies (E3).
V_MATRIX = [
    [(-1 + 1j) / 2, (-1 - 1j) / 2],
    [(-1 - 1j) / 2, (-1 + 1j) / 2],
]


def _from_matrix(m, basis, adjoint: bool = False):
    def go(v: Value) -> Vec:
        if v not in basis:
            return {}
        j = basis.index(v)
        if adjoint:  # column j of M-dagger is the conjugate of row j of M
            return {basis[i]: m[j][i].conjugate() for i in range(len(basis))}
        return {basis[i]: m[i][j] for i in range(len(basis))}

    return go


_prim("v", _from_matrix(V_MATRIX, BIT), _from_matrix(V_MATRIX, BIT, adjoint=True))


# ---------------------------------------------------------------------------
# Validation.
# ---------------------------------------------------------------------------


#: 42 primitives Q42 drops, and why.  Each is a real morphism of Rel and none is
#: unitary; `copy` is the interesting one, because it is not a no-cloning
#: violation -- it is a perfectly good isometry, just not a surjective one.
_DROPPED = {
    "zero": "the zero matrix is not unitary",
    "inl": "an injection is an isometry into a larger space, so it is not square",
    "inr": "an injection is an isometry into a larger space, so it is not square",
    "copy": (
        "the diagonal is an isometry but not a surjection, hence not unitary. "
        "It copies basis states only, so it is a measurement basis rather than "
        "an illegal cloner -- but it still has no adjoint that inverts it"
    ),
    "join": "the codiagonal is not unitary, and its converse was 42's only "
            "source of nondeterminism",
}


def validate(t: Term, where: str = "this term") -> None:
    """Reject the constructors that need an idempotent semiring.

    See the module docstring: `|` and `^` are not omitted by preference, they
    have no meaning over C.
    """
    match t:
        case Union(_, _):
            raise Q42Error(
                f"{where} uses `|`, which Q42 does not have: over C it would "
                f"denote the sum of two matrices, so `f | f` would be `2f`. "
                f"Superposition comes from `v`, not from choice."
            )
        case Star(_):
            raise Q42Error(
                f"{where} uses `^`, which Q42 does not have: a reflexive "
                f"transitive closure is a least fixed point over a lattice and "
                f"needs `1 + 1 = 1`, which is false in C."
            )
        case Seq(s, u) | Sum(s, u) | Prod(s, u) | App(s, u):
            validate(s, where)
            validate(u, where)
        case Fun(_, b):
            validate(b, where)
        case Prim(name, _):
            if name not in PRIMS:
                raise Q42Error(
                    f"{where} uses `{name}`, which is not a Q42 primitive "
                    f"(it is not unitary; see Q42.md section 2)"
                )
        case Ref(name, _):
            # A 42 primitive Q42 dropped parses as a reference here, because the
            # parser is given Q42's primitive names.  Say why rather than letting
            # it surface later as "undefined".
            if name in _DROPPED:
                raise Q42Error(
                    f"{where} uses `{name}`, a 42 primitive that Q42 does not "
                    f"have: {_DROPPED[name]}"
                )


# ---------------------------------------------------------------------------
# Evaluation.  `column(t, v)` is the column of [[t]] at basis index v.
# ---------------------------------------------------------------------------


def column(t: Term, v: Value, env: Dict[str, Term] | None = None,
           depth: int = 2000) -> Vec:
    """Apply `t` to a single basis value, giving a column of amplitudes.

    A basis value like `Pair(a, b)` is always a *product* state, which is why
    `Prod` may take the tensor of the two columns and stay correct.  Entangled
    states only arise when columns are summed, which happens in `apply_vec`.
    """
    env = {} if env is None else env

    if isinstance(t, Prim):
        pair = PRIMS.get(t.name)
        if pair is None:
            raise Q42Error(f"unknown primitive: {t.name}")
        return pair[1](v) if t.inv else pair[0](v)

    if isinstance(t, Ref):
        if depth <= 0:
            raise Q42Error(f"call depth exhausted while unfolding '{t.name}'")
        body = env.get(t.name)
        if body is None:
            raise Q42Error(f"undefined: {t.name}")
        return column(dagger(body) if t.inv else body, v, env, depth - 1)

    if isinstance(t, Seq):  # matrix product
        out: Vec = {}
        for w, zw in column(t.s, v, env, depth).items():
            for z, zz in column(t.t, w, env, depth).items():
                out[z] = out.get(z, 0) + zw * zz
        return normalise(out)

    if isinstance(t, Sum):  # direct sum
        if isinstance(v, Inl):
            return {Inl(w): z for w, z in column(t.s, v.v, env, depth).items()}
        if isinstance(v, Inr):
            return {Inr(w): z for w, z in column(t.t, v.v, env, depth).items()}
        return {}

    if isinstance(t, Prod):  # tensor product
        if not isinstance(v, Pair):
            return {}
        left = column(t.s, v.a, env, depth)
        if not left:
            return {}
        right = column(t.t, v.b, env, depth)
        return {
            Pair(a, b): za * zb
            for a, za in left.items()
            for b, zb in right.items()
        }

    validate(t)  # Union / Star produce their explanation here
    raise Q42Error(f"not a term: {t!r}")


def apply_vec(t: Term, psi: Vec, env: Dict[str, Term] | None = None) -> Vec:
    """Apply `t` to a superposition.

    Needed because `column` alone can never entangle: at a basis index the
    `Prod` rule decomposes, and it is summing columns that produces a state
    which is not a product.  42 never needed this, because applying a relation
    pointwise and taking the union *is* the whole story in Rel.
    """
    out: Vec = {}
    for v, amp in psi.items():
        for w, z in column(t, v, env).items():
            out[w] = out.get(w, 0) + amp * z
    return normalise(out)


# ---------------------------------------------------------------------------
# Measurement -- terminal only.
#
# This is deliberately *not* a term.  Measurement is not unitary, so admitting it
# into the language would end the property everything here rests on: that every
# term is invertible and `dagger` is total with no side conditions.  Instead it is
# an operation on a state that a program has already produced -- so no new
# constructor, no change to `dagger`, no change to the type system.
#
# The price is that it can only happen at the end.  Mid-circuit measurement with
# classical feedback -- what Shor, teleportation and error correction need -- would
# require stratifying the language into a unitary core and an effectful layer over
# it, which is a different piece of work (see QMANUAL.md section 9.2).
# ---------------------------------------------------------------------------


def probabilities(state: Vec) -> Dict[Value, float]:
    """The Born rule: the chance of seeing each outcome if you look.

    Returns the raw `|amplitude|^2` without renormalising.  For a state a Q42
    program produced these already sum to 1, because the input was a unit vector
    and every Q42 term is unitary -- so a total that is *not* 1 is evidence of a
    bug rather than something to paper over.
    """
    return {v: abs(z) ** 2 for v, z in state.items() if abs(z) > TOL}


def marginal(weights: Dict[Value, float], keep, label) -> Dict[str, float]:
    """The distribution over *some* of the qubits, the rest being ignored.

    Measuring only part of a register and discarding the rest leaves exactly this
    distribution on the part you kept -- summing the probabilities of every
    outcome that agrees on those positions. It stays a *terminal* measurement:
    nothing continues afterwards, so no collapsed residual state is needed.
    """
    out: Dict[str, float] = {}
    for v, p in weights.items():
        bits = label(v)
        if bits is None:
            return {}
        key = "".join(bits[i] if i in keep else "_" for i in range(len(bits)))
        out[key] = out.get(key, 0.0) + p
    return out


def sample(state: Vec, shots: int = 1, seed: int | None = None) -> Dict[Value, int]:
    """Draw `shots` outcomes from a state, as a real device would.

    `seed` fixes the draw, so a transcript in the documentation stays true.
    """
    import random

    weights = probabilities(state)
    if not weights:
        return {}
    rng = random.Random(seed)
    outcomes = list(weights)
    total = sum(weights.values())
    counts: Dict[Value, int] = {}
    for _ in range(shots):
        r, acc = rng.random() * total, 0.0
        for v in outcomes:
            acc += weights[v]
            if r <= acc:
                counts[v] = counts.get(v, 0) + 1
                break
    return counts


def matrix(t: Term, basis, env: Dict[str, Term] | None = None):
    """The full matrix of `t` over `basis`, as rows."""
    cols = [column(t, b, env) for b in basis]
    return [[cols[j].get(basis[i], 0) for j in range(len(basis))]
            for i in range(len(basis))]
