"""42 — a point-free reversible language interpreted in Rel.

Programs denote *relations*.  A term `t` denotes a morphism of Rel, and the
defining law of the language is

    x in run(t, y)   <=>   y in run(dagger(t), x)

i.e. `dagger` computes the converse relation.  Rel is a dagger category:
`dagger` is an identity-on-objects, involutive, contravariant functor, and
every rule below is forced by that fact rather than chosen.

Note what is *absent*: there are no well-formedness conditions, no exit
assertions, and no proof obligations.  Because nondeterministic choice
(`Union`) is a first-class construct, two branches never need a predicate to
separate them -- both are simply kept.  Dropping restrictions is what makes
`dagger` total.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Dict, Set


class Rel42Error(Exception):
    """Base class for every error this package raises."""


# ---------------------------------------------------------------------------
# Values.  The universe is generated by  0, 1, +, x  --  there are no
# inhabitants of 0, one inhabitant of 1, and sums/products build the rest.
# ---------------------------------------------------------------------------


class Value:
    __slots__ = ()


@dataclass(frozen=True)
class Unit(Value):
    """The unique inhabitant of the type 1."""


UNIT = Unit()


@dataclass(frozen=True)
class Inl(Value):
    """Left injection into a sum."""

    v: Value


@dataclass(frozen=True)
class Inr(Value):
    """Right injection into a sum."""

    v: Value


@dataclass(frozen=True)
class Pair(Value):
    """Inhabitant of a product."""

    a: Value
    b: Value


VSet = Set[Value]
EMPTY: VSet = frozenset()


# ---------------------------------------------------------------------------
# Terms.
# ---------------------------------------------------------------------------


class Term:
    __slots__ = ()


@dataclass(frozen=True)
class Prim(Term):
    """A primitive relation.  `inv` selects the converse leg of the pair."""

    name: str
    inv: bool = False


@dataclass(frozen=True)
class Ref(Term):
    """Reference to a (possibly recursive) definition."""

    name: str
    inv: bool = False


@dataclass(frozen=True)
class Seq(Term):
    """Relational composition, in diagrammatic order: `s` then `t`."""

    s: Term
    t: Term


@dataclass(frozen=True)
class Union(Term):
    """Nondeterministic choice -- union of two relations."""

    s: Term
    t: Term


@dataclass(frozen=True)
class Sum(Term):
    """The sum functor:  s (+) t  acts on Inl by s and on Inr by t."""

    s: Term
    t: Term


@dataclass(frozen=True)
class Prod(Term):
    """The product functor:  s (x) t  acts componentwise on a Pair."""

    s: Term
    t: Term


@dataclass(frozen=True)
class Star(Term):
    """Reflexive transitive closure."""

    s: Term


# --- abstraction over terms -------------------------------------------------
#
# 42 has no binders over *values*, and gains none here: `Fun` binds a name that
# stands for another term.  That is what lets a combinator like
#
#     def ctrl m = mat ; (id + m) ; mat!
#
# be written once instead of once per controlled gate.  Deliberately
# second-order: a parameter always denotes a relation `A <-> B`, never another
# function, which is enough for every use in the libraries and avoids needing
# variables at the level of iso types.


@dataclass(frozen=True)
class Var(Term):
    """A parameter of the enclosing `Fun`.  `inv` records a `!` written on it."""

    name: str
    inv: bool = False


@dataclass(frozen=True)
class Fun(Term):
    """`fun p -> body`, written `def f p = body`."""

    param: str
    body: Term


@dataclass(frozen=True)
class App(Term):
    """`f a` -- application of a term-level combinator to a term."""

    f: Term
    a: Term


# ---------------------------------------------------------------------------
# The dagger.  Total, structural, no side conditions.
# ---------------------------------------------------------------------------


def dagger(t: Term) -> Term:
    """The converse of a term.  `dagger(dagger(t)) == t` syntactically.

    Two of these cases deserve a word, because abstraction is the first thing
    added to 42 that inversion could plausibly have broken.

    `Var` flips, exactly like `Ref`.  PisoLang takes the other option and fixes
    variables under inversion (`phi^-1 := phi`), which is coherent but costs
    something 42 cannot afford: because `!` is eliminated at parse time, a
    variable that did not carry its own flag would make `m!` inside a body parse
    to the same term as `m`, silently.

    Having flipped the variable, `App` must then leave its *argument* alone --
    `dagger(f a) = dagger(f) a`, not `dagger(f) dagger(a)`. The two choices are
    a matched pair, and with this one

        dagger(ctrl) a  ==  mat ; (id! + a!) ; mat!

    which is the adjoint of `ctrl a`, and reads in physics as
    `(Ctrl U)-dagger = Ctrl U-dagger`.
    """
    match t:
        case Prim(n, i):
            return Prim(n, not i)
        case Ref(n, i):
            return Ref(n, not i)
        case Var(n, i):
            return Var(n, not i)
        case Seq(s, u):
            return Seq(dagger(u), dagger(s))  # contravariant: order flips
        case Union(s, u):
            return Union(dagger(s), dagger(u))
        case Sum(s, u):
            return Sum(dagger(s), dagger(u))
        case Prod(s, u):
            return Prod(dagger(s), dagger(u))
        case Star(s):
            return Star(dagger(s))
        case Fun(p, b):
            return Fun(p, dagger(b))
        case App(f, a):
            return App(dagger(f), a)  # the argument is inverted by substitution
    raise TypeError(f"not a term: {t!r}")


# ---------------------------------------------------------------------------
# Substitution and expansion.  Applications are reduced away *before*
# evaluation, so the evaluator never sees `Fun`, `App` or `Var` and did not
# have to change at all -- in rel42 or in q42.
# ---------------------------------------------------------------------------


def substitute(t: Term, name: str, arg: Term) -> Term:
    """Replace `Var(name)` by `arg`, honouring a `!` written on the variable.

    This is where the dagger of an argument is actually applied: `dagger` pushed
    the inversion onto the variable's flag, and substitution discharges it.
    """
    match t:
        case Var(n, i):
            if n != name:
                return t
            return dagger(arg) if i else arg
        case Seq(s, u):
            return Seq(substitute(s, name, arg), substitute(u, name, arg))
        case Union(s, u):
            return Union(substitute(s, name, arg), substitute(u, name, arg))
        case Sum(s, u):
            return Sum(substitute(s, name, arg), substitute(u, name, arg))
        case Prod(s, u):
            return Prod(substitute(s, name, arg), substitute(u, name, arg))
        case Star(s):
            return Star(substitute(s, name, arg))
        case Fun(p, b):
            return t if p == name else Fun(p, substitute(b, name, arg))
        case App(f, a):
            return App(substitute(f, name, arg), substitute(a, name, arg))
    return t


class NotARelation(Rel42Error):
    """A term denotes a combinator, not a relation, so it cannot be run."""


def expand(t: Term, env: Env | None = None, depth: int = 200) -> Term:
    """Reduce every application, leaving a term in the original language.

    A `Ref` is unfolded only when it heads an application, so ordinary recursive
    definitions are left for the evaluator to unfold lazily as before.
    """
    env = {} if env is None else env
    if depth <= 0:
        raise NotARelation("application depth exhausted; is a combinator recursive?")

    match t:
        case App(f, a):
            head = _as_fun(expand(f, env, depth), env, depth)
            arg = expand(a, env, depth)
            if head is None:
                raise NotARelation(
                    f"cannot apply {show_hint(f)}: it is not a combinator"
                )
            return expand(substitute(head.body, head.param, arg), env, depth - 1)
        case Fun(p, b):
            return Fun(p, expand(b, env, depth))
        case Seq(s, u):
            return Seq(expand(s, env, depth), expand(u, env, depth))
        case Union(s, u):
            return Union(expand(s, env, depth), expand(u, env, depth))
        case Sum(s, u):
            return Sum(expand(s, env, depth), expand(u, env, depth))
        case Prod(s, u):
            return Prod(expand(s, env, depth), expand(u, env, depth))
        case Star(s):
            return Star(expand(s, env, depth))
    return t


def expand_env(env: Env) -> Env:
    """Reduce every application in every definition, once, at load time.

    This is why neither evaluator needed a case for `App`: after this pass no
    application survives, and the only `Fun`s left are the combinators
    themselves, which are never run against a value.  Recursive definitions are
    untouched, because `expand` unfolds a `Ref` only when it heads an
    application.
    """
    out = {name: expand(body, env) for name, body in env.items()}
    types = getattr(env, "types", None)
    if types is None:
        return out
    return type(env)(out, types)  # keep any `type` abbreviations attached


def is_combinator(t: Term) -> bool:
    """Does this term take a parameter, rather than denoting a relation?"""
    return isinstance(t, Fun)


def _as_fun(t: Term, env: Env, depth: int) -> "Fun | None":
    """The `Fun` a term reduces to at the head, or None."""
    if isinstance(t, Fun):
        return t
    if isinstance(t, Ref):
        body = env.get(t.name)
        if body is None:
            return None
        if t.inv:
            body = dagger(body)
        got = expand(body, env, depth - 1)
        return got if isinstance(got, Fun) else None
    return None


# ---------------------------------------------------------------------------
# Primitives.  Each is a pair (forward, backward) of  Value -> set of Value.
# A shape mismatch returns the empty set: in Rel, being outside the domain of
# a relation is not an error, it is simply having no image.
# ---------------------------------------------------------------------------

PRIMS: Dict[str, tuple[Callable[[Value], VSet], Callable[[Value], VSet]]] = {}


def _prim(name: str, fwd, bwd) -> None:
    PRIMS[name] = (fwd, bwd)


# identity and the empty relation ------------------------------------------
_prim("id", lambda v: {v}, lambda v: {v})
_prim("zero", lambda v: EMPTY, lambda v: EMPTY)


# additive structure --------------------------------------------------------
def _swapsum(v: Value) -> VSet:
    match v:
        case Inl(x):
            return {Inr(x)}
        case Inr(x):
            return {Inl(x)}
    return EMPTY


_prim("swapsum", _swapsum, _swapsum)  # self-inverse


def _assocsum(v: Value) -> VSet:  # a + (b + c)  ->  (a + b) + c
    match v:
        case Inl(x):
            return {Inl(Inl(x))}
        case Inr(Inl(x)):
            return {Inl(Inr(x))}
        case Inr(Inr(x)):
            return {Inr(x)}
    return EMPTY


def _assocsum_b(v: Value) -> VSet:  # (a + b) + c  ->  a + (b + c)
    match v:
        case Inl(Inl(x)):
            return {Inl(x)}
        case Inl(Inr(x)):
            return {Inr(Inl(x))}
        case Inr(x):
            return {Inr(Inr(x))}
    return EMPTY


_prim("assocsum", _assocsum, _assocsum_b)


def _unitsum(v: Value) -> VSet:  # 0 + a  ->  a   (the 0 side is uninhabited)
    match v:
        case Inr(x):
            return {x}
    return EMPTY


_prim("unitsum", _unitsum, lambda v: {Inr(v)})


# multiplicative structure --------------------------------------------------
def _swapprod(v: Value) -> VSet:
    match v:
        case Pair(a, b):
            return {Pair(b, a)}
    return EMPTY


_prim("swapprod", _swapprod, _swapprod)  # self-inverse


def _assocprod(v: Value) -> VSet:  # (a, (b, c))  ->  ((a, b), c)
    match v:
        case Pair(a, Pair(b, c)):
            return {Pair(Pair(a, b), c)}
    return EMPTY


def _assocprod_b(v: Value) -> VSet:  # ((a, b), c)  ->  (a, (b, c))
    match v:
        case Pair(Pair(a, b), c):
            return {Pair(a, Pair(b, c))}
    return EMPTY


_prim("assocprod", _assocprod, _assocprod_b)


def _unitprod(v: Value) -> VSet:  # 1 x a  ->  a
    match v:
        case Pair(Unit(), x):
            return {x}
    return EMPTY


_prim("unitprod", _unitprod, lambda v: {Pair(UNIT, v)})


# distributivity ------------------------------------------------------------
def _dist(v: Value) -> VSet:  # (a + b) x c  ->  (a x c) + (b x c)
    match v:
        case Pair(Inl(a), c):
            return {Inl(Pair(a, c))}
        case Pair(Inr(b), c):
            return {Inr(Pair(b, c))}
    return EMPTY


def _dist_b(v: Value) -> VSet:
    match v:
        case Inl(Pair(a, c)):
            return {Pair(Inl(a), c)}
        case Inr(Pair(b, c)):
            return {Pair(Inr(b), c)}
    return EMPTY


_prim("dist", _dist, _dist_b)


# injections.  Partial injections, not bijections: inl's converse is undefined
# on Inr.  This is where partiality enters the language.
def _inl_b(v: Value) -> VSet:
    match v:
        case Inl(x):
            return {x}
    return EMPTY


def _inr_b(v: Value) -> VSet:
    match v:
        case Inr(x):
            return {x}
    return EMPTY


_prim("inl", lambda v: {Inl(v)}, _inl_b)
_prim("inr", lambda v: {Inr(v)}, _inr_b)


# The two morphisms that make this Rel rather than a groupoid ---------------
# copy: the diagonal.  Its converse is the partial "these agree" projection.
def _copy_b(v: Value) -> VSet:
    match v:
        case Pair(a, b) if a == b:
            return {a}
    return EMPTY


_prim("copy", lambda v: {Pair(v, v)}, _copy_b)


# join: the codiagonal.  Its converse is genuinely nondeterministic -- it is
# the only primitive whose backward image can have two elements, and it is the
# source of every set larger than a singleton in the language.
def _join(v: Value) -> VSet:
    match v:
        case Inl(x) | Inr(x):
            return {x}
    return EMPTY


_prim("join", _join, lambda v: {Inl(v), Inr(v)})


# ---------------------------------------------------------------------------
# Evaluation.
# ---------------------------------------------------------------------------


class DepthExceeded(Rel42Error):
    """A closure or an unfolding did not saturate within the given budget.

    This is not a bug to be papered over.  A relation in Rel may be computable
    in one direction and not the other -- `pred*` saturates at zero, while its
    converse `succ*` is the infinite set of all larger numbers -- so the
    interpreter reports non-saturation rather than pretending to be total.
    """


Env = Dict[str, Term]


def show_hint(t: Term) -> str:
    """A rough name for a term, for error messages only.

    `rel42.syntax.show_term` is the real printer; core must not import it.
    """
    match t:
        case Prim(n, i) | Ref(n, i):
            return n + ("!" if i else "")
    return type(t).__name__.lower()


@dataclass
class _Ctx:
    env: Env
    cache: dict
    max_orbit: int


def run(
    t: Term,
    v: Value,
    env: Env | None = None,
    max_depth: int = 5000,
    max_orbit: int = 1000,
) -> VSet:
    """Apply the relation denoted by `t` to `v`, returning its image set.

    `max_orbit` bounds how large a `Star` closure may grow before the
    interpreter concludes it will not saturate.  It is deliberately modest:
    values are nested structures whose hashing cost grows with their depth, so
    a large bound trades a fast honest answer for a slow one.
    """
    ctx = _Ctx(env if env is not None else {}, {}, max_orbit)
    return _apply(t, v, ctx, max_depth)


def _apply(t: Term, v: Value, ctx: _Ctx, depth: int) -> VSet:
    env, cache = ctx.env, ctx.cache
    if isinstance(t, Prim):
        pair = PRIMS.get(t.name)
        if pair is None:
            raise Rel42Error(f"unknown primitive: {t.name}")
        return pair[1](v) if t.inv else pair[0](v)

    if isinstance(t, Ref):
        if depth <= 0:
            raise DepthExceeded(
                f"call depth exhausted while unfolding '{t.name}' "
                f"(raise --limit if the program really is this deep)"
            )
        body = env.get(t.name)
        if body is None:
            raise Rel42Error(f"undefined: {t.name}")
        if t.inv:
            key = ("dagger", t.name)
            body = cache.get(key) or cache.setdefault(key, dagger(body))
        return _apply(body, v, ctx, depth - 1)

    if isinstance(t, Seq):
        out: set = set()
        for w in _apply(t.s, v, ctx, depth):
            out |= _apply(t.t, w, ctx, depth)
        return out

    if isinstance(t, Union):
        return _apply(t.s, v, ctx, depth) | _apply(t.t, v, ctx, depth)

    if isinstance(t, Sum):
        if isinstance(v, Inl):
            return {Inl(w) for w in _apply(t.s, v.v, ctx, depth)}
        if isinstance(v, Inr):
            return {Inr(w) for w in _apply(t.t, v.v, ctx, depth)}
        return EMPTY

    if isinstance(t, Prod):
        if not isinstance(v, Pair):
            return EMPTY
        left = _apply(t.s, v.a, ctx, depth)
        if not left:
            return EMPTY
        right = _apply(t.t, v.b, ctx, depth)
        return {Pair(a, b) for a in left for b in right}

    if isinstance(t, Star):
        seen = {v}
        frontier = {v}
        while frontier:
            nxt: set = set()
            for w in frontier:
                for z in _apply(t.s, w, ctx, depth):
                    if z not in seen:
                        seen.add(z)
                        nxt.add(z)
            if len(seen) > ctx.max_orbit:
                raise DepthExceeded(
                    f"closure of '{show_hint(t.s)}' passed {ctx.max_orbit} elements "
                    f"without saturating; it is probably infinite in this direction"
                )
            frontier = nxt
        return seen

    if isinstance(t, (Fun, App, Var)):
        raise NotARelation(
            f"{show_hint(t)} is a combinator, not a relation: it takes a "
            f"parameter, so it cannot be applied to a value"
        )
    raise Rel42Error(f"not a term: {t!r}")
