"""Types for 42 -- shapes for the relations that terms denote.

A term denotes a relation, so its type has two sides:

    t : A <-> B      means    [[t]]  is a subset of  A x B

Types are the trees generated by the same four things the values are:

    0            uninhabited
    1            one inhabitant
    A + B        labelled
    A x B        paired

plus variables, because the plumbing is polymorphic (`swapprod` rearranges any
pair, so its type is `a x b <-> b x a`), plus `mu X. F(X)` for the recursive
ones, because `nat` and `list` are not finite trees.

Recursion is **equirecursive**: `mu X. F(X)` and `F(mu X. F(X))` are the same
type, silently, with no `fold`/`unfold` in the language and no change to any
program that was already written.  A `mu` is not a construct the programmer
reaches for -- it is what the checker *infers* when unification closes a loop.
`nat` is not declared anywhere; it appears because `succ = inr` composed with
itself demands it.

Four things are worth stating up front, because each is forced by the setting
rather than chosen, and each is checked in tests/test_types.py.

**Inversion swaps the two sides.**  If `t : A <-> B` then `t! : B <-> A`, and
nothing else about the type changes.  This is the type-level shadow of the
defining law: `dagger` is contravariant on composition and identity-on-objects,
so at the level of shapes it can only exchange domain and codomain.  Inference
implements `inv` by literally swapping a scheme, so the property holds by
construction.

**Generalisation is nearly trivial, because 42 has almost no binders.**  Every
definition is a closed term -- no lambda, no local name -- so a non-recursive
definition generalises over all its free variables and none of the usual
machinery (levels, ranks, the value restriction) is needed.  The one exception is
a group of mutually recursive definitions, which are typed together against
*monomorphic* assumptions and generalised only once the group is done.  That is
Milner-style recursion: polymorphic recursion is undecidable in general, and
nothing in the libraries wants it.

**A cycle in unification is the recursive type, not a failure.**  Where a
finite-tree checker runs an occurs check and gives up, this one binds the
variable to a term containing itself and carries on; the cycle *is* `mu`.  So
`downfrom = pred^` demands `b = a + b` and gets `mu X. a + X`.  Unification then
has to work up to unfolding, which it does coinductively: assume the two sides
equal, and check that the assumption survives one layer.  The set of assumptions
is what makes it terminate.

**But a cycle still has to be read before it is trusted.**  Not every recursive
equation describes a type with values in it:

    b = a + b     is  mu X. a + X   -- a list.  Has finite values.
    a = a x a     is  mu X. X x X   -- infinite trees only.  Has none.

The first is a good type; the second is a fault in the program that no amount of
recursion will rescue, and `copy^` is how you write it.  They are told apart by
one unfolding with the recursive variable taken to be empty: `mu X. F(X)` has a
finite value exactly when `F(0)` does.  If `F(0)` is empty then so is `F(F(0))`,
so one step settles it.

Internally a recursive type is a *cycle in the substitution* rather than a `TMu`
node -- that is what makes unification fall out of ordinary variable binding.
`TMu` appears only in the canonical form, produced by `Inference.apply` when a
type is read out of the solver for storing or printing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, FrozenSet, Iterator, List, Sequence, Set, Tuple

from .core import (
    App,
    Fun,
    Inl,
    Inr,
    Pair,
    Prim,
    Prod,
    Ref,
    Rel42Error,
    Seq,
    Star,
    Sum,
    Term,
    Unit,
    Union,
    Value,
    Var,
)


# ---------------------------------------------------------------------------
# Types.
# ---------------------------------------------------------------------------


class Type:
    __slots__ = ()


@dataclass(frozen=True)
class TVar(Type):
    """A variable.  Free ones are generalised; `TMu` binds one."""

    id: int


@dataclass(frozen=True)
class TZero(Type):
    """The empty type.  No values inhabit it."""


@dataclass(frozen=True)
class TOne(Type):
    """The unit type.  `()` is its only value."""


@dataclass(frozen=True)
class TSum(Type):
    a: Type
    b: Type


@dataclass(frozen=True)
class TProd(Type):
    a: Type
    b: Type


@dataclass(frozen=True)
class TMu(Type):
    """`mu var. body` -- equal to its own unfolding, and never written by hand."""

    var: int
    body: Type


@dataclass(frozen=True)
class Scheme:
    """A type for a term.

    A relation has `params = ()` and reads `dom <-> cod`.  A combinator carries
    one `(dom, cod)` pair per parameter, outermost first, and reads

        (a <-> b) -> (c <-> d)

    No general arrow type is needed, and that falls out of the second-order
    restriction in `core`: a parameter always denotes a relation, never another
    combinator, so a combinator's type is fully described by a list of parameter
    relation-types plus the relation it finally denotes.

    Generalised over every free variable, except while a recursive group is
    being solved: `mono` marks an assumption that must be used as-is rather
    than freshened at each occurrence.
    """

    dom: Type
    cod: Type
    mono: bool = False
    params: Tuple[Tuple[Type, Type], ...] = ()

    @property
    def is_combinator(self) -> bool:
        return bool(self.params)

    def swap(self) -> "Scheme":
        """The type of the dagger.

        The parameters are *not* swapped, only the result.  That is forced by
        `core.dagger`'s convention: inversion pushes onto the variable's flag and
        substitution discharges it, so `dagger(ctrl)` still accepts an argument of
        the same type and returns the adjoint of what `ctrl` returned.
        """
        return Scheme(self.cod, self.dom, self.mono, self.params)


# ---------------------------------------------------------------------------
# Errors.
# ---------------------------------------------------------------------------


class IllTyped(Rel42Error):
    """Two shapes clash, or a recursive type would have no values.

    Either way the program is wrong.  At runtime it would denote the empty
    relation, which is a legitimate morphism of Rel, so the interpreter cannot
    report it; that silence is exactly what a type system is for.
    """


# ---------------------------------------------------------------------------
# Primitive schemes.  These *are* the isomorphisms witnessing the commutative
# semiring structure of (0, 1, +, x), which is why the table reads like the
# semiring axioms: that is what the primitives were chosen to be.
# ---------------------------------------------------------------------------

_a, _b, _c = TVar(0), TVar(1), TVar(2)

PRIM_SCHEMES: Dict[str, Scheme] = {
    # identity, and the empty relation between any two shapes at all
    "id": Scheme(_a, _a),
    "zero": Scheme(_a, _b),
    # additive structure
    "swapsum": Scheme(TSum(_a, _b), TSum(_b, _a)),
    "assocsum": Scheme(TSum(_a, TSum(_b, _c)), TSum(TSum(_a, _b), _c)),
    "unitsum": Scheme(TSum(TZero(), _a), _a),
    # multiplicative structure
    "swapprod": Scheme(TProd(_a, _b), TProd(_b, _a)),
    "assocprod": Scheme(TProd(_a, TProd(_b, _c)), TProd(TProd(_a, _b), _c)),
    "unitprod": Scheme(TProd(TOne(), _a), _a),
    # distributivity
    "dist": Scheme(
        TProd(TSum(_a, _b), _c), TSum(TProd(_a, _c), TProd(_b, _c))
    ),
    # injections: partial injections, so the other summand is unconstrained
    "inl": Scheme(_a, TSum(_a, _b)),
    "inr": Scheme(_b, TSum(_a, _b)),
    # the two that make this Rel rather than a groupoid
    "copy": Scheme(_a, TProd(_a, _a)),
    "join": Scheme(TSum(_a, _a), _a),
}


# ---------------------------------------------------------------------------
# Operations on canonical (TMu-carrying) types.
# ---------------------------------------------------------------------------


def unfold(t: TMu) -> Type:
    """One layer off a `mu`.  Equirecursively this changes nothing."""
    return replace_var(t.body, t.var, t)


def replace_var(t: Type, i: int, repl: Type) -> Type:
    """Substitute for a free occurrence of variable `i`, respecting binders."""
    match t:
        case TVar(j):
            return repl if i == j else t
        case TSum(a, b):
            return TSum(replace_var(a, i, repl), replace_var(b, i, repl))
        case TProd(a, b):
            return TProd(replace_var(a, i, repl), replace_var(b, i, repl))
        case TMu(v, body):
            return t if v == i else TMu(v, replace_var(body, i, repl))
    return t


def _mus_in(t: Type) -> Iterator[TMu]:
    """Every `mu` node anywhere in `t`.

    Not just the immediate children: the list case hides its recursion one level
    down, in `1 + a x (mu X. 1 + a x X)`, where the `mu` sits inside the product.
    """
    if isinstance(t, TMu):
        yield t
    match t:
        case TSum(a, b) | TProd(a, b):
            yield from _mus_in(a)
            yield from _mus_in(b)
        case TMu(_, body):
            yield from _mus_in(body)


def refold(t: Type) -> Type:
    """Collapse `F(mu X. F(X))` back to `mu X. F(X)`.

    Equirecursive types have no unique syntactic form, and canonicalising one
    properly means minimising a regular tree.  This is the cheap half: it
    recognises a type that is literally one unfolding of a `mu` occurring inside
    it, which is the shape unification leaves behind whenever it closes a loop
    below the root -- `pred^` produces `a + (mu X. a + X)` and means
    `mu X. a + X`.

    Deeper coincidences are left alone.  `mu X. b + (a + X)` and
    `mu Y. a + (b + Y)` denote the same infinite tree but no single unfolding
    relates them, so both may appear in one file.  That is wordier than
    necessary, never wrong.
    """
    match t:
        case TSum(a, b):
            folded: Type = TSum(refold(a), refold(b))
        case TProd(a, b):
            folded = TProd(refold(a), refold(b))
        case TMu(v, body):
            folded = TMu(v, refold(body))
        case _:
            return t
    for m in _mus_in(folded):
        if unfold(m) == folded:
            return m
    return folded


def inhabited(t: Type, empty: FrozenSet[int] = frozenset()) -> bool:
    """Does this type have any finite value?

    `empty` holds recursive variables taken to be uninhabited, which is what
    makes `mu X. X x X` come out false and `mu X. 1 + X` come out true.  A free
    variable counts as inhabited: it is universally quantified, so it stands for
    whatever the caller supplies, and nothing here should decide otherwise.
    """
    match t:
        case TZero():
            return False
        case TOne():
            return True
        case TVar(i):
            return i not in empty
        case TSum(a, b):
            return inhabited(a, empty) or inhabited(b, empty)
        case TProd(a, b):
            return inhabited(a, empty) and inhabited(b, empty)
        case TMu(v, body):
            return inhabited(body, empty | {v})
    return True


# ---------------------------------------------------------------------------
# Inference.
# ---------------------------------------------------------------------------


class Inference:
    """Unification state for one run of the checker.

    Kept as an object rather than threaded through as arguments because the
    substitution and the fresh-variable counter are both single-writer and
    every rule touches them.  The substitution may be *cyclic*: that is how a
    recursive type is represented while being solved.
    """

    def __init__(self, prims: Dict[str, Scheme] | None = None) -> None:
        self.subst: Dict[int, Type] = {}
        self._next = 1000  # above the small ids used in PRIM_SCHEMES
        # The primitive signatures.  Injected so that a sibling language over the
        # same term grammar -- q42, whose primitives are unitaries rather than
        # relations -- reuses this engine whole rather than forking it.
        self.prims = PRIM_SCHEMES if prims is None else prims

    # -- variables ---------------------------------------------------------

    def fresh(self) -> TVar:
        self._next += 1
        return TVar(self._next)

    def resolve(self, t: Type) -> Type:
        """Follow variable bindings at the root only.

        Terminates even with a cyclic substitution: a variable is only ever
        bound while unbound, so a chain of pure variable indirections cannot
        close into a loop, and any cycle passes through a constructor.
        """
        while isinstance(t, TVar) and t.id in self.subst:
            t = self.subst[t.id]
        return t

    def apply(self, t: Type) -> Type:
        """Read a type out of the solver, in canonical form.

        Any cycle reached on the way becomes an explicit `mu`.  This is the only
        place `TMu` is built.
        """
        return refold(self._canon(t, ())[0])

    def _canon(self, t: Type, path: Tuple[int, ...]) -> Tuple[Type, Set[int]]:
        """Expand `t`, returning it and the path variables it loops back to."""
        if isinstance(t, TVar):
            if t.id in path:
                return t, {t.id}  # a back-edge: some binder above owns this
            if t.id in self.subst:
                body, used = self._canon(self.subst[t.id], path + (t.id,))
                if t.id in used:
                    return TMu(t.id, body), used - {t.id}
                return body, used
            return t, set()
        match t:
            case TSum(a, b):
                ca, ua = self._canon(a, path)
                cb, ub = self._canon(b, path)
                return TSum(ca, cb), ua | ub
            case TProd(a, b):
                ca, ua = self._canon(a, path)
                cb, ub = self._canon(b, path)
                return TProd(ca, cb), ua | ub
            case TMu(v, body):
                cb, used = self._canon(body, path)
                return TMu(v, cb), used - {v}
        return t, set()

    def instantiate(self, s: Scheme) -> Scheme:
        """Freshen every variable.  Both sides share one renaming.

        A monomorphic assumption -- a member of the recursive group currently
        being solved -- is returned untouched, which is what ties the recursive
        occurrences to the definition being checked.
        """
        if s.mono:
            return s
        mapping: Dict[int, TVar] = {}

        def go(t: Type) -> Type:
            match t:
                case TVar(i):
                    return mapping.setdefault(i, self.fresh())
                case TSum(a, b):
                    return TSum(go(a), go(b))
                case TProd(a, b):
                    return TProd(go(a), go(b))
                case TMu(v, body):
                    # The binder is renamed like anything else; consistently,
                    # so the body's back-references still point at it.
                    return TMu(mapping.setdefault(v, self.fresh()).id, go(body))
            return t

        return Scheme(
            go(s.dom),
            go(s.cod),
            params=tuple((go(a), go(b)) for a, b in s.params),
        )

    # -- unification -------------------------------------------------------

    def occurs(
        self, i: int, t: Type, seen: FrozenSet[Type] = frozenset()
    ) -> bool:
        """Does variable `i` appear in `t`?

        `seen` plays the role `assumed` plays in `unify`.  Substitutions here
        are deliberately cyclic -- that is what makes the types equirecursive --
        so a naive walk follows a cycle forever.  Cutting at an already-visited
        node is sound because this is a reachability question: arriving somewhere
        twice on one path cannot reveal an occurrence the first visit missed.
        """
        t = self.resolve(t)
        if t in seen:
            return False
        seen = seen | {t}
        match t:
            case TVar(j):
                return i == j
            case TSum(a, b) | TProd(a, b):
                return self.occurs(i, a, seen) or self.occurs(i, b, seen)
            case TMu(v, body):
                return i != v and self.occurs(i, body, seen)
        return False

    def unify(
        self,
        x: Type,
        y: Type,
        why: str,
        assumed: FrozenSet[Tuple[Type, Type]] = frozenset(),
    ) -> None:
        """Unify up to unfolding of `mu`.

        `assumed` carries the coinductive hypotheses: pairs already taken to be
        equal further up this derivation.  Without it, two recursive types would
        unfold against each other forever; with it, the recursion is bounded by
        the number of distinct resolved pairs, which is finite for the regular
        trees a cyclic substitution can describe.
        """
        x, y = self.resolve(x), self.resolve(y)
        if x == y or (x, y) in assumed:
            return
        assumed = assumed | {(x, y)}

        if isinstance(x, TVar):
            self._bind(x, y, why)
            return
        if isinstance(y, TVar):
            self._bind(y, x, why)
            return

        # A `mu` is equal to its unfolding, so peel and continue.  The
        # assumption added above is what stops this from being circular.
        if isinstance(x, TMu):
            return self.unify(unfold(x), y, why, assumed)
        if isinstance(y, TMu):
            return self.unify(x, unfold(y), why, assumed)

        match (x, y):
            case (TSum(a, b), TSum(c, d)) | (TProd(a, b), TProd(c, d)):
                self.unify(a, c, why, assumed)
                self.unify(b, d, why, assumed)
                return

        names = _label(x, y)
        raise IllTyped(
            f"{why}: cannot match {show_type(x, names)} "
            f"with {show_type(y, names)}"
        )

    def _bind(self, x: TVar, y: Type, why: str) -> None:
        """Bind a variable, allowing a cycle -- but only an inhabited one.

        Binding `X := F(X)` is how a recursive type is created, and it is
        usually right.  It is wrong exactly when `mu X. F(X)` has no finite
        values, because then the program has demanded something no value can
        satisfy.  See the module docstring.
        """
        if self.occurs(x.id, y):
            body = self.apply(y)
            if not inhabited(replace_var(body, x.id, TZero())):
                shown = show_type(body, _label(body, pin=x.id))
                raise IllTyped(
                    f"{why}: X would have to equal {shown}, and mu X. {shown} "
                    f"has no finite values -- no recursive type can rescue this"
                )
        self.subst[x.id] = y

    def generalise(self, s: Scheme) -> Scheme:
        """Read a whole type out of the solver, in canonical form."""
        return Scheme(
            self.apply(s.dom),
            self.apply(s.cod),
            params=tuple((self.apply(a), self.apply(b)) for a, b in s.params),
        )

    def relation(
        self, t: Term, env: Dict[str, Scheme], where: str
    ) -> Tuple[Type, Type]:
        """Infer `t` and insist it denotes a relation rather than a combinator.

        Every operator of the language composes relations, so an unapplied
        combinator in any of those positions is a missing argument.
        """
        s = self.infer(t, env)
        if s.params:
            raise IllTyped(
                f"{where} is a combinator awaiting {len(s.params)} more "
                f"argument(s), not a relation"
            )
        return s.dom, s.cod

    def unify_scheme(self, x: Scheme, y: Scheme, why: str) -> None:
        """Unify two whole types, parameters included."""
        if len(x.params) != len(y.params):
            raise IllTyped(
                f"{why}: one takes {len(x.params)} parameter(s) and the other "
                f"{len(y.params)}"
            )
        for (a, b), (c, d) in zip(x.params, y.params):
            self.unify(a, c, why)
            self.unify(b, d, why)
        self.unify(x.dom, y.dom, why)
        self.unify(x.cod, y.cod, why)

    # -- the rules ---------------------------------------------------------

    def infer(self, t: Term, env: Dict[str, Scheme]) -> Scheme:
        """The type of a term.

        One rule per constructor, and each is the obvious one -- `;` matches the
        middle, `|` matches both ends, `+` and `*` are functors, `^` forces the
        two ends together, and `!` swaps them.  Abstraction and application add
        two more, and `params` on `Scheme` is all the machinery they need.
        """
        match t:
            case Prim(name, inv):
                if name not in self.prims:
                    raise Rel42Error(f"unknown primitive: {name}")
                s = self.prims[name]
                return self.instantiate(s.swap() if inv else s)

            case Ref(name, inv) | Var(name, inv):
                if name not in env:
                    raise Rel42Error(f"undefined: {name}")
                s = env[name]
                return self.instantiate(s.swap() if inv else s)

            case Fun(param, body):
                # The parameter denotes a relation of unknown shape.  It is a
                # *monomorphic* assumption: a combinator uses its argument at one
                # type, which is what makes this decidable.
                a, b = self.fresh(), self.fresh()
                inner = self.infer(body, {**env, param: Scheme(a, b, mono=True)})
                return Scheme(
                    inner.dom, inner.cod, params=((a, b),) + inner.params
                )

            case App(f, arg):
                fs = self.infer(f, env)
                if not fs.params:
                    raise IllTyped(
                        "this is applied to an argument but takes no parameters"
                    )
                (pa, pb), rest = fs.params[0], fs.params[1:]
                got = self.infer(arg, env)
                if got.params:
                    raise IllTyped(
                        "a combinator cannot be passed as an argument: 42 is "
                        "second-order, so a parameter must denote a relation"
                    )
                self.unify(got.dom, pa, "in an application (the argument's domain)")
                self.unify(got.cod, pb, "in an application (the argument's codomain)")
                return Scheme(fs.dom, fs.cod, params=rest)

            case Seq(s, u):
                a, b = self.relation(s, env, "the left of a composition `;`")
                c, d = self.relation(u, env, "the right of a composition `;`")
                self.unify(b, c, "in a composition `;`")
                return Scheme(a, d)

            case Union(s, u):
                a, b = self.relation(s, env, "the left of a choice `|`")
                c, d = self.relation(u, env, "the right of a choice `|`")
                # Both branches are alternatives for the *same* relation, so
                # both ends must agree.
                self.unify(a, c, "in a choice `|` (the two domains differ)")
                self.unify(b, d, "in a choice `|` (the two codomains differ)")
                return Scheme(a, b)

            case Sum(s, u):
                a, b = self.relation(s, env, "the left of `+`")
                c, d = self.relation(u, env, "the right of `+`")
                return Scheme(TSum(a, c), TSum(b, d))

            case Prod(s, u):
                a, b = self.relation(s, env, "the left of `*`")
                c, d = self.relation(u, env, "the right of `*`")
                return Scheme(TProd(a, c), TProd(b, d))

            case Star(s):
                a, b = self.relation(s, env, "the body of a closure `^`")
                # A closure iterates, so it must be composable with itself.
                # This is where `pred^` acquires  nat = mu X. 1 + X.
                self.unify(a, b, "in a closure `^` (it must map a type to itself)")
                return Scheme(a, a)

        raise Rel42Error(f"not a term: {t!r}")


# ---------------------------------------------------------------------------
# Whole programs.
# ---------------------------------------------------------------------------


def references(t: Term) -> Set[str]:
    """Every definition named anywhere in a term."""
    out: Set[str] = set()
    stack: List[Term] = [t]
    while stack:
        u = stack.pop()
        match u:
            case Ref(name, _):
                out.add(name)
            case Seq(s, v) | Union(s, v) | Sum(s, v) | Prod(s, v) | App(s, v):
                stack += [s, v]
            case Star(s) | Fun(_, s):
                stack.append(s)
    return out


def _arity(t: Term) -> int:
    """How many parameters a definition takes."""
    return 1 + _arity(t.body) if isinstance(t, Fun) else 0


def groups(defs: Dict[str, Term]) -> List[List[str]]:
    """Mutually recursive groups, dependencies first (Tarjan).

    A group of one that does not name itself is an ordinary definition.
    Anything else is recursive and must be solved as a unit.
    """
    deps = {n: references(b) & defs.keys() for n, b in defs.items()}
    index: Dict[str, int] = {}
    low: Dict[str, int] = {}
    onstack: Dict[str, bool] = {}
    stack: List[str] = []
    out: List[List[str]] = []
    counter = 0

    def strong(v: str) -> None:
        nonlocal counter
        index[v] = low[v] = counter
        counter += 1
        stack.append(v)
        onstack[v] = True
        for w in sorted(deps[v]):
            if w not in index:
                strong(w)
                low[v] = min(low[v], low[w])
            elif onstack.get(w):
                low[v] = min(low[v], index[w])
        if low[v] == index[v]:
            comp: List[str] = []
            while True:
                w = stack.pop()
                onstack[w] = False
                comp.append(w)
                if w == v:
                    break
            out.append(sorted(comp))

    for n in defs:
        if n not in index:
            strong(n)
    return out


def infer_program(
    defs: Dict[str, Term], prims: Dict[str, Scheme] | None = None
) -> Tuple[Dict[str, Scheme], Dict[str, Exception]]:
    """Type every definition it can, and report why the rest failed.

    Deliberately does not stop at the first error: on a file of twenty
    definitions the useful output is which nineteen were fine.
    """
    schemes: Dict[str, Scheme] = {}
    errors: Dict[str, Exception] = {}

    for comp in groups(defs):
        blocked = sorted(
            {
                m
                for n in comp
                for m in (references(defs[n]) & defs.keys())
                if m not in comp and m not in schemes
            }
        )
        if blocked:
            for n in comp:
                errors[n] = IllTyped(
                    f"depends on {', '.join(blocked)}, which did not typecheck"
                )
            continue

        inf = Inference(prims)
        recursive = len(comp) > 1 or comp[0] in references(defs[comp[0]])
        try:
            if not recursive:
                name = comp[0]
                schemes[name] = inf.generalise(inf.infer(defs[name], schemes))
            else:
                # Monomorphic assumptions for the whole group, then solve the
                # bodies against them.  Generalise only once all are consistent.
                assume = {
                    n: Scheme(
                        inf.fresh(),
                        inf.fresh(),
                        mono=True,
                        params=tuple(
                            (inf.fresh(), inf.fresh()) for _ in range(_arity(defs[n]))
                        ),
                    )
                    for n in comp
                }
                env = {**schemes, **assume}
                for n in comp:
                    got = inf.infer(defs[n], env)
                    why = f"in the recursive definition of `{n}`"
                    inf.unify_scheme(got, assume[n], why)
                for n in comp:
                    schemes[n] = inf.generalise(assume[n])
        except Rel42Error as e:
            for n in comp:
                errors.setdefault(n, e)
    return schemes, errors


def infer_term(
    t: Term, env: Dict[str, Scheme], prims: Dict[str, Scheme] | None = None
) -> Scheme:
    """The type of a single term against already-typed definitions."""
    inf = Inference(prims)
    return inf.generalise(inf.infer(t, env))


# ---------------------------------------------------------------------------
# Do values fit types?
# ---------------------------------------------------------------------------


def conform(
    v: Value, t: Type, seen: FrozenSet[Tuple[int, Type]] = frozenset()
) -> Tuple[Value, Type] | None:
    """`None` if `v` inhabits `t`; otherwise the innermost pair that clashed.

    A free variable accepts anything.  It is universally quantified, so the
    caller chooses what it stands for, and a value is evidence of that choice
    rather than a violation of it -- `succ : a <-> b + a` really does accept any
    value at all on the left.

    A `mu` is checked by unfolding, which terminates because every recursive
    type that survived `Inference._bind` is guarded: one unfolding exposes a
    constructor, which consumes a layer of the (finite) value.  `seen` guards
    the pathological case anyway rather than trusting that argument.
    """
    match t:
        case TVar(_):
            return None
        case TOne():
            return None if isinstance(v, Unit) else (v, t)
        case TZero():
            return v, t  # nothing inhabits 0
        case TSum(a, b):
            if isinstance(v, Inl):
                return conform(v.v, a, seen)
            if isinstance(v, Inr):
                return conform(v.v, b, seen)
            return v, t
        case TProd(a, b):
            if not isinstance(v, Pair):
                return v, t
            return conform(v.a, a, seen) or conform(v.b, b, seen)
        case TMu(_, _):
            key = (id(v), t)
            if key in seen:
                return v, t
            return conform(v, unfold(t), seen | {key})
    return v, t


def names_for(*ts: Type) -> Dict[int, str]:
    """Canonical variable names, shared across several types so they line up."""
    return _label(*ts)


# ---------------------------------------------------------------------------
# Abbreviations.
#
# Inferred types are correct and nearly unreadable:
#
#     divmod : (mu X. a + X) x (b + (mu Y. 1 + Y)) <-> ...
#
# Declaring `type nat = mu X. 1 + X` lets the printer say `nat` instead.  This is
# a *display* layer and nothing more: no new primitives, no new semantics, and
# the checker behaves identically whether or not any abbreviation is declared.
#
# Matching has to be up to equirecursive equality, because the same infinite tree
# has many presentations -- `nat`, `1 + nat`, and the shifted forms `refold`
# cannot collapse.  Unification already decides that question, so `match_type`
# is unification's one-way sibling: pattern variables listed in `params` may
# bind, everything else must agree on the nose.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Abbrev:
    """`type name p1 p2 = body`."""

    name: str
    params: Tuple[int, ...]
    body: Type


def match_type(
    pattern: Type,
    subject: Type,
    params: FrozenSet[int],
    subst: Dict[int, Type] | None = None,
    seen: FrozenSet[Tuple[Type, Type]] = frozenset(),
) -> Dict[int, Type] | None:
    """One-way match, up to unfolding.  `None` if the shapes differ.

    Unlike `unify` this never binds a variable of the *subject*: an abbreviation
    must describe the type it is offered, not constrain it.  Without that,
    `type nat = mu X. 1 + X` would match every type variable and every inferred
    type would print as `nat`.
    """
    subst = {} if subst is None else subst
    if (pattern, subject) in seen:
        return subst
    seen = seen | {(pattern, subject)}

    if isinstance(pattern, TVar) and pattern.id in params:
        bound = subst.get(pattern.id)
        if bound is None:
            subst[pattern.id] = subject
            return subst
        return subst if match_type(bound, subject, frozenset(), {}, seen) else None

    if isinstance(pattern, TMu):
        return match_type(unfold(pattern), subject, params, subst, seen)
    if isinstance(subject, TMu):
        return match_type(pattern, unfold(subject), params, subst, seen)

    match (pattern, subject):
        case (TZero(), TZero()) | (TOne(), TOne()):
            return subst
        case (TVar(i), TVar(j)):
            return subst if i == j else None
        case (TSum(a, b), TSum(c, d)) | (TProd(a, b), TProd(c, d)):
            if match_type(a, c, params, subst, seen) is None:
                return None
            return match_type(b, d, params, subst, seen)
    return None


# ---------------------------------------------------------------------------
# Printing.  `+` binds looser than `x`, matching the term grammar, so a sum
# inside a product needs brackets and nothing else does.  `mu` is looser still.
# ---------------------------------------------------------------------------

# `x` is the product operator in type syntax, so it is not available as a
# variable name -- `(x + x) x (a + b)` would be unreadable and unparseable.
_LETTERS = "abcdefghijklmnopqrstuvwyz"
_BOUND = "XYZWVU"


def _label(*ts: Type, pin: int | None = None) -> Dict[int, str]:
    """Names for the variables in `ts`.

    Recursive binders get `X`, `Y`, ... and free variables `a`, `b`, ..., so
    that reading a printed type tells you which is which.  `pin` names one
    variable `X` up front, for messages about a cycle not yet turned into a
    `TMu`.
    """
    free: List[int] = []
    bound: List[int] = []

    def walk(t: Type) -> None:
        match t:
            case TVar(i):
                free.append(i)
            case TSum(a, b) | TProd(a, b):
                walk(a)
                walk(b)
            case TMu(v, body):
                bound.append(v)
                walk(body)

    for t in ts:
        walk(t)

    out: Dict[int, str] = {}
    n = 0
    if pin is not None:
        out[pin] = _BOUND[0]
        n = 1
    for i in bound:
        if i not in out:
            out[i] = _BOUND[n] if n < len(_BOUND) else f"X{n}"
            n += 1
    m = 0
    for i in free:
        if i not in out:
            out[i] = _LETTERS[m] if m < len(_LETTERS) else f"t{m}"
            m += 1
    return out


def _names(s: Scheme) -> Dict[int, str]:
    return _label(*[x for pair in s.params for x in pair], s.dom, s.cod)


def show_type(
    t: Type,
    names: Dict[int, str] | None = None,
    ctx: int = 0,
    abbrevs: Sequence["Abbrev"] = (),
    depth: int = 12,
) -> str:
    """Render a type.

    `abbrevs` are tried at every node, in declaration order, first match winning
    -- so declare the more specific ones first.

    Neither `+` nor `x` is associative here -- `(a x b) x c` and `a x (b x c)`
    are different shapes, and `assocprod` is the term that converts between
    them -- so the printer must not silently flatten either one.  Both are shown
    left-associatively, matching the term grammar, and a right-nested operand is
    bracketed.

    `ctx` is the tightest level that still prints bare: 0 sums and `mu`,
    1 products, 2 atoms only.
    """
    if depth > 0:
        for ab in abbrevs:
            found = match_type(ab.body, t, frozenset(ab.params))
            if found is None:
                continue
            if not ab.params:
                return ab.name
            args = " ".join(
                show_type(found.get(p, TVar(p)), names, 2, abbrevs, depth - 1)
                for p in ab.params
            )
            return f"({ab.name} {args})" if ctx > 1 else f"{ab.name} {args}"

    def go(u: Type, c: int) -> str:
        return show_type(u, names, c, abbrevs, depth - 1)

    match t:
        case TVar(i):
            return names[i] if names and i in names else f"?{i}"
        case TZero():
            return "0"
        case TOne():
            return "1"
        case TMu(v, body):
            name = names[v] if names and v in names else f"?{v}"
            s = f"mu {name}. {go(body, 0)}"
            return f"({s})" if ctx > 0 else s
        case TSum(a, b):
            s = f"{go(a, 0)} + {go(b, 1)}"
            return f"({s})" if ctx > 0 else s
        case TProd(a, b):
            s = f"{go(a, 1)} x {go(b, 2)}"
            return f"({s})" if ctx > 1 else s
    raise Rel42Error(f"not a type: {t!r}")


def show_scheme(s: Scheme, abbrevs: Sequence["Abbrev"] = ()) -> str:
    names = _label(*[x for pair in s.params for x in pair], s.dom, s.cod)

    def one(t: Type) -> str:
        return show_type(t, names, 0, abbrevs)

    body = f"{one(s.dom)} <-> {one(s.cod)}"
    if not s.params:
        return body
    args = " -> ".join(f"({one(a)} <-> {one(b)})" for a, b in s.params)
    return f"{args} -> ({body})"
