#!/usr/bin/env python3
"""Turn a generated `qterm` value into Q42 source -- the *quote/unquote* bridge.

Not to be confused with `q42/emit.py`, which is the other direction entirely:
this one turns 42 *data* into Q42 *text*, and that one turns a Q42 *term* into
gates for a device.

The whole of the seam between the two languages.  `qft.42` computes a circuit as
42 *data*; a Q42 program is a *term*; values and terms are different things, in
the implementation and in the semantics, so something outside both languages has
to cross between them.  This is that something, and it is twenty lines because
42 and Q42 already share the parser and the type checker -- the output is fed
straight back to `42q type` and `42q unitary`, which are the same checkers the
handwritten libraries use.

    $ tools/unquote.py qft.42 aqft 2
    ((h * id) ; (ctrl ((s * t)) ; (id * ((h * id) ; (ctrl (s) ; (id * h))))))

    $ tools/unquote.py qft.42 aqft 2 --file > q42/qft3.42
    $ ./42q unitary q42/qft3.42
"""

from __future__ import annotations

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from rel42.core import Inl, Inr, Pair, expand_env, run
from rel42.syntax import from_nat, parse_program

#: The atoms of `qterm`, in the order the type declares them.
ATOMS = ["id", "h", "z", "s", "t"]

#: A self-contained preamble, so the generated file needs no include mechanism.
PREAMBLE = """\
def x      = swapsum
def mat    = dist ; (unitprod + unitprod)
def ctrl m = mat ; (id + m) ; mat!
def s      = id + (omega ; omega)
def t      = id + omega
def z      = id + (omega ; omega ; omega ; omega)
def hcore  = x ; s ; v ; s ; x
def h      = unitprod! ; (omega * hcore) ; unitprod
"""


def _index(v):
    """Which arm of the atom sum this is, by counting right injections."""
    k = 0
    while isinstance(v, Inr):
        v, k = v.v, k + 1
    return k


def emit(v) -> str:
    match v:
        case Inl(Inl(a)):
            return ATOMS[_index(a)]
        case Inl(Inr(t)):
            return f"ctrl ({emit(t)})"
        case Inr(Inl(Pair(a, b))):
            return f"({emit(a)} ; {emit(b)})"
        case Inr(Inr(Pair(a, b))):
            return f"({emit(a)} * {emit(b)})"
    raise ValueError(f"not a qterm: {v}")


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("file", help="the 42 program that generates the family")
    p.add_argument("main", help="the generator, a definition of type nat <-> qterm")
    p.add_argument("n", type=int, help="the index of the family member")
    p.add_argument("--file", dest="whole", action="store_true",
                   help="emit a complete, runnable Q42 file")
    p.add_argument("--name", default="main", help="name for the generated definition")
    a = p.parse_args(argv)

    with open(a.file, "r", encoding="utf-8") as fh:
        env = expand_env(parse_program(fh.read()))
    results = run(env[a.main], from_nat(a.n), env)
    if len(results) != 1:
        print(f"error: {a.main}({a.n}) has {len(results)} results, expected 1",
              file=sys.stderr)
        return 1
    body = emit(next(iter(results)))

    if a.whole:
        print(f"-- generated by  tools/unquote.py {a.file} {a.main} {a.n}")
        print(f"-- do not edit; edit {a.file} and regenerate\n")
        print(PREAMBLE)
        print(f"def {a.name} = {body}")
    else:
        print(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
